export const SYSTEM_ROLE_LIST = 'SYSTEM_ROLE_LIST';
export const SYSTEM_ROLE_STATUS = 'SYSTEM_ROLE_STATUS';
export const SYSTEM_ROLE_SCANALL = 'SYSTEM_ROLE_SCANALL';
export const SYSTEM_DICTIONARY_LIST = 'SYSTEM_DICTIONARY_LIST';

export const MONTHLY_ILLEGAL_LIST = 'MONTHLY_ILLEGAL_LIST';

export const LANGUAGE = 'LANGUAGE';

export const LOOKUP_PLACE = 'LOOKUP_PLACE';
export const LOOKUP_EXITORENTRY = 'LOOKUP_EXITORENTRY';
export const LOOKUP_AGE = 'LOOKUP_AGE';
export const LOOKUP_SEX = 'LOOKUP_SEX';
export const LOOKUP_CASHTYPE = 'LOOKUP_CASHTYPE';
export const LOOKUP_CURRENCYTYPE = 'LOOKUP_CURRENCYTYPE';
export const LOOKUP_CERTIFICATETYPE = 'LOOKUP_CERTIFICATETYPE';
export const LOOKUP_LOCAL = 'LOOKUP_LOCAL';// 行动地点--->local
export const LOOKUP_TEAM = 'LOOKUP_TEAM';// 参与行动组-->team
export const LOOKUP_OCORRENCIA = 'LOOKUP_OCORRENCIA';// 事件-->ocorrencia
export const LOOKUP_STATE = 'LOOKUP_STATE';// 状态-->state
